version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/jwt-prisma
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jwt-prisma
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
  node_modules:
